# This is a basic workflow to help you get started with Actions

name: "Pull dans la branche dev"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Création du porteclé SSH
  create_ssh:
    name: "Création du SSH"

    runs-on: ubuntu-latest

    steps:
      - name: "Create private SSH key"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa.key
          chmod 600 ~/.ssh/id_rsa.key
          cat >>~/.ssh/config <<END
            Host serveurDev
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/id_rsa.key
              StrictHostKeyChecking no
          END
      - name: "Connexion au serveur de dev"
        run: |
          ssh serveurDev 'cd /home/debian/Cube && git fetch && git pull'
